DELETE FROM Exemplifica;
DELETE FROM Coocorrencia;
DELETE FROM Pertence;
DELETE FROM Palavra;
DELETE FROM Frase;
DELETE FROM Propriedade;
DELETE FROM Dependencia;
DELETE FROM Ficheiro;
DELETE FROM Corpus;