-- MySQL Script generated by MySQL Workbench
-- Thu Mar 19 22:47:08 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_deep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_deep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_deep` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_deep` ;

-- -----------------------------------------------------
-- Table `db_deep`.`Corpus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deep`.`Corpus` (
  `idCorpus` INT NOT NULL AUTO_INCREMENT,
  `Nome` VARCHAR(45) NOT NULL,
  `Fonte` VARCHAR(45) NULL,
  `Data` DATETIME NULL,
  `GeneroTextual` VARCHAR(45) NULL,
  PRIMARY KEY (`idCorpus`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Palavra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deep`.`Palavra` (
  `idPalavra` INT NOT NULL AUTO_INCREMENT,
  `Palavra` VARCHAR(45) NOT NULL,
  `Lema` VARCHAR(45) NOT NULL,
  `etiquetaMorfossintatica` VARCHAR(45) NULL,
  `categoria` VARCHAR(45) NULL,
  `frequencia` INT NOT NULL,
  `Corpus_idCorpus` INT NOT NULL,
  PRIMARY KEY (`idPalavra`, `Corpus_idCorpus`),
  INDEX `fk_Palavra_Corpus_idx` (`Corpus_idCorpus` ASC),
  CONSTRAINT `fk_Palavra_Corpus`
    FOREIGN KEY (`Corpus_idCorpus`)
    REFERENCES `db_deep`.`Corpus` (`idCorpus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Dependencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deep`.`Dependencia` (
  `idDependencia` INT NOT NULL AUTO_INCREMENT,
  `tipoDependencia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDependencia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Co-ocorrencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deep`.`Co-ocorrencia` (
  `idCo-ocorrencia` INT NOT NULL AUTO_INCREMENT,
  `Frequencia` INT NOT NULL,
  `Dependencia_idDependencia` INT NOT NULL,
  `Palavra_idPalavra` INT NOT NULL,
  `Palavra_Corpus_idCorpus` INT NOT NULL,
  `idPalavra2` INT NOT NULL,
  PRIMARY KEY (`idCo-ocorrencia`, `Dependencia_idDependencia`, `Palavra_idPalavra`, `Palavra_Corpus_idCorpus`),
  INDEX `fk_Co-ocorrencia_Dependencia1_idx` (`Dependencia_idDependencia` ASC),
  INDEX `fk_Co-ocorrencia_Palavra1_idx` (`Palavra_idPalavra` ASC, `Palavra_Corpus_idCorpus` ASC),
  CONSTRAINT `fk_Co-ocorrencia_Dependencia1`
    FOREIGN KEY (`Dependencia_idDependencia`)
    REFERENCES `db_deep`.`Dependencia` (`idDependencia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Co-ocorrencia_Palavra1`
    FOREIGN KEY (`Palavra_idPalavra` , `Palavra_Corpus_idCorpus`)
    REFERENCES `db_deep`.`Palavra` (`idPalavra` , `Corpus_idCorpus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Frase`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_deep`.`Frase` (
  `idFrase` INT NOT NULL AUTO_INCREMENT,
  `frase` VARCHAR(45) NOT NULL,
  `Co-ocorrencia_idCo-ocorrencia` INT NOT NULL,
  `Co-ocorrencia_Dependencia_idDependencia` INT NOT NULL,
  `Co-ocorrencia_Palavra_idPalavra` INT NOT NULL,
  `Co-ocorrencia_Palavra_Corpus_idCorpus` INT NOT NULL,
  PRIMARY KEY (`idFrase`, `Co-ocorrencia_idCo-ocorrencia`, `Co-ocorrencia_Dependencia_idDependencia`, `Co-ocorrencia_Palavra_idPalavra`, `Co-ocorrencia_Palavra_Corpus_idCorpus`),
  INDEX `fk_Frase_Co-ocorrencia1_idx` (`Co-ocorrencia_idCo-ocorrencia` ASC, `Co-ocorrencia_Dependencia_idDependencia` ASC, `Co-ocorrencia_Palavra_idPalavra` ASC, `Co-ocorrencia_Palavra_Corpus_idCorpus` ASC),
  CONSTRAINT `fk_Frase_Co-ocorrencia1`
    FOREIGN KEY (`Co-ocorrencia_idCo-ocorrencia` , `Co-ocorrencia_Dependencia_idDependencia` , `Co-ocorrencia_Palavra_idPalavra` , `Co-ocorrencia_Palavra_Corpus_idCorpus`)
    REFERENCES `db_deep`.`Co-ocorrencia` (`idCo-ocorrencia` , `Dependencia_idDependencia` , `Palavra_idPalavra` , `Palavra_Corpus_idCorpus`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
