-- MySQL Script generated by MySQL Workbench
-- Tue Apr 21 01:00:03 2015
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_deep
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_deep
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_deep` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `db_deep` ;

-- -----------------------------------------------------
-- Table `db_deep`.`Corpus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_deep`.`Corpus` ;

CREATE TABLE IF NOT EXISTS `db_deep`.`Corpus` (
  `nome` VARCHAR(45) NOT NULL,
  `fonte` VARCHAR(45) NULL,
  `ano` VARCHAR(45) NULL,
  `genero` VARCHAR(45) NULL,
  `update` TINYINT(1) NOT NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Palavra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_deep`.`Palavra` ;

CREATE TABLE IF NOT EXISTS `db_deep`.`Palavra` (
  `idPalavra` BIGINT NOT NULL,
  `palavra` VARCHAR(45) NOT NULL,
  `lema` VARCHAR(45) NOT NULL,
  `classe` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NULL,
  `frequencia` INT NOT NULL,
  `Corpus_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPalavra`),
  INDEX `fk_Palavra_Corpus1_idx` (`Corpus_nome` ASC),
  CONSTRAINT `fk_Palavra_Corpus1`
    FOREIGN KEY (`Corpus_nome`)
    REFERENCES `db_deep`.`Corpus` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Frase`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_deep`.`Frase` ;

CREATE TABLE IF NOT EXISTS `db_deep`.`Frase` (
  `idFrase` BIGINT NOT NULL,
  `frase` VARCHAR(400) NOT NULL,
  `Corpus_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idFrase`),
  INDEX `fk_Frase_Corpus1_idx` (`Corpus_nome` ASC),
  CONSTRAINT `fk_Frase_Corpus1`
    FOREIGN KEY (`Corpus_nome`)
    REFERENCES `db_deep`.`Corpus` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Dependencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_deep`.`Dependencia` ;

CREATE TABLE IF NOT EXISTS `db_deep`.`Dependencia` (
  `tipoDep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipoDep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Propriedade`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_deep`.`Propriedade` ;

CREATE TABLE IF NOT EXISTS `db_deep`.`Propriedade` (
  `tipoProp` VARCHAR(45) NOT NULL,
  `_tipoDep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`tipoProp`, `_tipoDep`),
  INDEX `fk_Propriedade_Dependencia1_idx` (`_tipoDep` ASC),
  CONSTRAINT `fk_Propriedade_Dependencia1`
    FOREIGN KEY (`_tipoDep`)
    REFERENCES `db_deep`.`Dependencia` (`tipoDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`Co-ocorrencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_deep`.`Co-ocorrencia` ;

CREATE TABLE IF NOT EXISTS `db_deep`.`Co-ocorrencia` (
  `_idPalavra1` BIGINT NOT NULL,
  `_idPalavra2` BIGINT NOT NULL,
  `_tipoProp` VARCHAR(45) NOT NULL,
  `_tipoDep` VARCHAR(45) NOT NULL,
  `frequencia` INT NOT NULL,
  `PMI` DOUBLE NOT NULL,
  `Dice` DOUBLE NOT NULL,
  `LogDice` DOUBLE NOT NULL,
  `ChiPearson` DOUBLE NOT NULL,
  `LogLikelihood` DOUBLE NOT NULL,
  `Significance` DOUBLE NOT NULL,
  INDEX `fk_Palavra_has_Palavra_Palavra2_idx` (`_idPalavra2` ASC),
  INDEX `fk_Palavra_has_Palavra_Palavra1_idx` (`_idPalavra1` ASC),
  PRIMARY KEY (`_idPalavra1`, `_idPalavra2`, `_tipoProp`, `_tipoDep`),
  INDEX `fk_Co-ocorrencia_Propriedade1_idx` (`_tipoProp` ASC, `_tipoDep` ASC),
  CONSTRAINT `fk_Palavra_has_Palavra_Palavra1`
    FOREIGN KEY (`_idPalavra1`)
    REFERENCES `db_deep`.`Palavra` (`idPalavra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Palavra_has_Palavra_Palavra2`
    FOREIGN KEY (`_idPalavra2`)
    REFERENCES `db_deep`.`Palavra` (`idPalavra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Co-ocorrencia_Propriedade1`
    FOREIGN KEY (`_tipoProp` , `_tipoDep`)
    REFERENCES `db_deep`.`Propriedade` (`tipoProp` , `_tipoDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_deep`.`exemplos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `db_deep`.`exemplos` ;

CREATE TABLE IF NOT EXISTS `db_deep`.`exemplos` (
  `_idPalavra1` BIGINT NOT NULL,
  `_idPalavra2` BIGINT NOT NULL,
  `_tipoProp` VARCHAR(45) NOT NULL,
  `_tipoDep` VARCHAR(45) NOT NULL,
  `Frase_idFrase` BIGINT NOT NULL,
  PRIMARY KEY (`_idPalavra1`, `_idPalavra2`, `_tipoProp`, `_tipoDep`, `Frase_idFrase`),
  INDEX `fk_exemplos_Co-ocorrencia1_idx` (`_idPalavra1` ASC, `_idPalavra2` ASC, `_tipoProp` ASC, `_tipoDep` ASC),
  INDEX `fk_exemplos_Frase1_idx` (`Frase_idFrase` ASC),
  CONSTRAINT `fk_exemplos_Co-ocorrencia1`
    FOREIGN KEY (`_idPalavra1` , `_idPalavra2` , `_tipoProp` , `_tipoDep`)
    REFERENCES `db_deep`.`Co-ocorrencia` (`_idPalavra1` , `_idPalavra2` , `_tipoProp` , `_tipoDep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_exemplos_Frase1`
    FOREIGN KEY (`Frase_idFrase`)
    REFERENCES `db_deep`.`Frase` (`idFrase`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
