/**
 * 
 */
package pt.inescid.l2f.xipapi.domain;

import org.w3c.dom.Document;
import org.w3c.dom.Element;

/**
 * API to handle the XML generated by the XIP program.
 * 
 * <P>An Anaphor is a leaf node stored within a Dependency node. 
 * 	 It stores information about anaphoric relations.
 *  
 * @author Filipe Carapinha [2012/May]
 * @version 1.0
 */
public class Anaphor {

	//##############################################################################
	//   ###########################################################################
	//      ATTRIBUTES
	//   ###########################################################################
	//##############################################################################

	/** The node number of the anaphor */
	private String nodeNumber;

	/** The string corresponding to the anaphor */
	private String value;


	//##############################################################################
	//   ###########################################################################
	//      CONSTUCTORS
	//   ###########################################################################
	//##############################################################################

	/**
	 * Constructor.
	 * 
	 * @param nodeNumber   Number of the anaphor node.
	 * @param value        String corresponding to the anaphor (antecedent).
	 */
	public Anaphor(String nodeNumber, String value){
		this.nodeNumber = nodeNumber;
		this.value = value;
	}


	//##############################################################################
	//   ###########################################################################
	//      GETTERS AND SETTERS
	//   ###########################################################################
	//##############################################################################

	/**
	 * Getter.
	 * @return string corresponding to the anaphor
	 */
	public String getValue(){
		return this.value;
	}

	/**
	 * Getter.
	 * @return the node number of the anaphor
	 */
	public String getNodeNumber(){
		return this.nodeNumber;
	}


	//##############################################################################
	//   ###########################################################################
	//      CONVERTERS
	//   ###########################################################################
	//##############################################################################

	/**
	 * XML Output function.
	 * 
	 * Filipe Carapinha [2012/Sep]
	 */	
	public void exportXMLDOM(Element parent, Document doc){
		Element thisNode = doc.createElement("ANAPHOR");
		thisNode.setAttribute("nodeNumber", this.nodeNumber);
		thisNode.setAttribute("value", this.value);

		parent.appendChild(thisNode);
	}

}
